[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "cd backend && npm install && npx prisma generate"
]

[start]
cmd = "node backend/src/index.js"
